### ISSUE TITLE
No Module named ldap_query

### ISSUE THREAD

**Issue by donslice** [deralexxx/FireMISP#4]
Hey there. Just did a git pull and am trying to run the script. Getting this error and can't find a corresponding module to go with it.

```
Traceback (most recent call last):
  File "firemisp.py", line 22, in <module>
    from ldap_query import search_host_and_fqdn, search_userprinciplename, search_for_mail
ImportError: No module named ldap_query
```
Any help would be appreciated.

Thanks!

**Comment by jaegeral** [comment]
yep indeed, give some days, I will update the whole thing including the ldap query part.

**Comment by donslice** [comment]
Very cool. Thanks!


On Mar 24, 2017, 10:16 AM -0400, Alexander J <notifications@github.com>, wrote:

yep indeed, give some days, I will update the whole thing including the ldap query part.

**Comment by korrosivesec** [comment]
@deralexxx had a chance to add that ldap_query library yet?

**Comment by jaegeral** [comment]
try it now, I removed the dependency for now

**Comment by donslice** [comment]
No change. Last commit shows in December still?

**Comment by jaegeral** [comment]
now :)

**Comment by donslice** [comment]
Looks like that worked. Thanks!
